version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
      - MONGO_URI=mongodb://mongodb:27017/air-quality-index
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - WAQI_API_KEY=ac21802e68e99e31c2d8aa5fb6f19cb496d3e581
      - DATA_FILE_PATH=data/waqi-covid-2023.csv

  mongodb:
    image: mongo:latest
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # We map the ports so we can access them if needed from our host system
      - "15672:15672" # Management plugin UI

  worker:
    build: .
    hostname: worker
    entrypoint: celery
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
      - MONGO_URI=mongodb://mongodb:27017/air-quality-index
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - WAQI_API_KEY=ac21802e68e99e31c2d8aa5fb6f19cb496d3e581
      - DATA_FILE_PATH=data/waqi-covid-2023.csv
    command: -A src.app.celery worker --loglevel=info
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data:
